### ISSUE TITLE
Update the heading and title to InnovateEd

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/NSCC-BKBIET-Git-GitHub#3]
This is the most easiest one. Go pick it up! Comment below! 👇🏻

**Comment by Manjeet-Agarwal** [comment]
amazing

**Comment by naveenkumar006100** [comment]
✋🏻

**Comment by praveenscience** [comment]
@IamPrakharRajawat Go for it.

**Comment by setco-website** [comment]
@IamPrakharRajawat doesn't have a laptop, so I would like to do it. 💪🏻

**Comment by praveenscience** [comment]
@setco-website Go for it.
